### ISSUE TITLE
[Bug]: Error: Uncaught TypeError: Cannot read properties of undefined (reading 'isComic')

### ISSUE THREAD

**Issue by YoukaiKowai** [ollm/OpenComic#262]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

Windows 10 22H2 Build 19045.4780

### Steps to reproduce

Open any Manga .cbz archive.

### Expected Behavior

It should open normally without any issues.

### Actual Behavior

Instead, it freezes like this.

![opencomic ss1](https://github.com/user-attachments/assets/10e0b8b0-1848-48a1-b13e-de2a79079dd3)

### Error message

It shows this error when I try to exit OpenComic.

```
Error: Uncaught TypeError: Cannot read properties of undefined (reading 'isComic') at linenumber 1251:10 of file C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\dom.js
TypeError: Cannot read properties of undefined (reading 'isComic')
    at Object.indexPathControlUpdateLastComic (C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\dom.js:1251:10)
    at saveReadingProgress (C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:3194:6)
    at Object.saveReadingProgress (C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:3167:4)
    at HTMLSpanElement.onclick (file:///C:/Users/***/AppData/Local/Programs/OpenComic/resources/app.asar/templates/index.html:1:9)
```

### Additional Information

This doesn't happen with every manga archive, so please let me know if you need the actual files where this issue occurs.

**Comment by YoukaiKowai** [comment]
Update: The problem was solved by extracting the archive and renaming the folder. Please, delete this issue.

**Comment by ollm** [comment]
Please can you try the following master build, although you have solved the problem by extracting the `cbz` file, OpenComic should open `cbz` files without any errors.

If still happening, you can send me the `cbz` to this email: oleguer.llopart.mora@gmail.com

Build: https://mega.nz/file/rbZEgbRI#rGbM2her1XlWFlQf9ZbAuJZSt8NOiOo359TQOMr8w-A

**Comment by YoukaiKowai** [comment]
The master version works perfectly. Thank you!

**Comment by ollm** [comment]
The error is because OpenComic was not checking if the file existed when trying to open the last read when the `Open directly in continue reading instead of the file list (Folders)` option was enabled, this could also happen when going forward and back, this should fix it 2948ac64e6153ac8934ca15839cefbbedd7a7a40

Build: https://mega.nz/file/3LpggAiR#2PpO6FUjIEfW7yP6QEpTQ4Te6b4boUyILffOr24fMl4

**Comment by dajotim937** [comment]
> The error is because OpenComic was not checking if the file existed when

When you open cbz file in OpenComic, delete file using explorer and then file->open file location throw error.

**Comment by ollm** [comment]
This build should fix both bugs cc337f20a53e78320b256e89ccc31a2d27cda890

Also includes the change of `copyToTmp` to `fileToBlob` c8086ba5525ce389aba86891fa241c731babdd2c mentioned in https://github.com/ollm/OpenComic/issues/241#issuecomment-2308178469, I've done some tests and there is no noticeable difference in performance, the hard drive would have to be much slower than the main drive to appreciate it.

Build: https://mega.nz/file/eaZjlLbS#RB4lE9ZYM2nYv6oyN8JRc8-8D5-6HDMVnX-ZtnzBvbA

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
