### ISSUE TITLE
[Bug]: The app is completely frozen

### ISSUE THREAD

**Issue by Envy91122** [ollm/OpenComic#474]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.6.3-1

### Operating System

Arch linux

### Installed via

AUR

### Steps to reproduce

1. Run Opencomic
2. Open any local file
3. The app is completely frozen

<img width="1101" height="674" alt="Image" src="https://github.com/user-attachments/assets/d86fd725-dbb1-48c5-b82d-a10640e904a0" />

### Expected Behavior

-

### Actual Behavior

-

### Error message

[24994:1010/004335.120996:ERROR:ui/gl/gl_surface_presentation_helper.cc:260] GetVSyncParametersIfAvailable() failed for 1 times!
[24994:1010/004336.822618:ERROR:ui/gl/gl_surface_presentation_helper.cc:260] GetVSyncParametersIfAvailable() failed for 2 times!
[24994:1010/004337.971689:ERROR:ui/gl/gl_surface_presentation_helper.cc:260] GetVSyncParametersIfAvailable() failed for 3 times!

### Additional Information

<img width="894" height="640" alt="Image" src="https://github.com/user-attachments/assets/71fa5f11-a208-498c-a600-26c0661d4004" />

### Sample file

-

**Comment by ollm** [comment]
It seems to be the same issue as #472.

I'll try to release a new version with the fix as soon as possible.

**Comment by ollm** [comment]
Can you try the new version `v1.6.4`? The issue should be fixed.

**Comment by Envy91122** [comment]
opencomic-bin 1.6.4-1 in AUR. The problem has not fixed

<img width="888" height="581" alt="Image" src="https://github.com/user-attachments/assets/03ab07a9-a3a2-4401-bda2-57d6e7def7d2" />

Error log:

```
[1947:1012/181407.974296:ERROR:ui/ozone/common/egl_util.cc:58] Failed to load GLES library: /opt/opencomic-bin/libGLESv2.so: /opt/opencomic-bin/libGLESv2.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
[1947:1012/181407.978826:ERROR:components/viz/service/main/viz_main_impl.cc:189] Exiting GPU process due to errors during initialization
[1975:1012/181408.103204:ERROR:ui/ozone/common/egl_util.cc:58] Failed to load GLES library: /opt/opencomic-bin/libGLESv2.so: /opt/opencomic-bin/libGLESv2.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
[1975:1012/181408.103791:ERROR:components/viz/service/main/viz_main_impl.cc:189] Exiting GPU process due to errors during initialization
[1984:1012/181408.112392:ERROR:ui/ozone/common/egl_util.cc:58] Failed to load GLES library: /opt/opencomic-bin/libGLESv2.so: /opt/opencomic-bin/libGLESv2.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
[1984:1012/181408.113055:ERROR:components/viz/service/main/viz_main_impl.cc:189] Exiting GPU process due to errors during initialization
[2000:1012/181408.198300:ERROR:ui/ozone/common/egl_util.cc:58] Failed to load GLES library: /opt/opencomic-bin/libGLESv2.so: /opt/opencomic-bin/libGLESv2.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
[2000:1012/181408.198926:ERROR:components/viz/service/main/viz_main_impl.cc:189] Exiting GPU process due to errors during initialization
[2007:1012/181408.205309:ERROR:ui/ozone/common/egl_util.cc:58] Failed to load GLES library: /opt/opencomic-bin/libGLESv2.so: /opt/opencomic-bin/libGLESv2.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
[2007:1012/181408.205926:ERROR:components/viz/service/main/viz_main_impl.cc:189] Exiting GPU process due to errors during initialization
Warning: win.show() from did-finish-load and not from ready-to-show
```

невозможно открыть разделяемый объектный файл: Нет такого файла или каталога - cannot open shared object file: No such file or directory

**Comment by ollm** [comment]
For now, I can't reproduce it on a virtual machine with Arch Linux.

I see that you can open `About OpenComic`. If you start OpenComic without opening any file, try going to `Debug` > `Toggle DevTools` to see if any errors appear when the app freezes.

Also, you can try whether the Flathub/Flatpak version works: https://flathub.org/en/apps/app.opencomic.OpenComic

**Comment by woducku** [comment]
@ollm flathub one is still `v1.6.3`

**Comment by ollm** [comment]
Although it's on version `v1.6.3`, it includes the fix released with version `v1.6.4`. This is because I first submitted the update to Flathub without increasing the version number, as I initially believed the Wayland issue only affected the Flatpak/Flathub version #472

**Comment by Envy91122** [comment]
I deleted opencomic-bin `1.6.4-1` and downloaded opencomic `1.6.4-1` (NOT BIN) (AUR)
Error log: 
```
Warning: win.show() from did-finish-load and not from ready-to-show
[29928:1013/205801.601707:ERROR:CONSOLE:1] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[29928:1013/205801.601766:ERROR:CONSOLE:1] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[29960:1013/205803.627540:ERROR:ui/gl/gl_surface_presentation_helper.cc:260] GetVSyncParametersIfAvailable() failed for 1 times!
[29960:1013/205808.446612:ERROR:ui/gl/gl_surface_presentation_helper.cc:260] GetVSyncParametersIfAvailable() failed for 2 times!
[29960:1013/205812.393545:ERROR:ui/gl/gl_surface_presentation_helper.cc:260] GetVSyncParametersIfAvailable() failed for 3 times!
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:94282)
    at b.send (node:electron/js2c/browser_init:2:78703)
    at Timeout._onTimeout (/usr/lib/opencomic/app.asar/scripts/main.js:186:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
```
I don't found errors in debug console, but I record this

[Recording 13.10.2025 at 20_58_05.js](https://github.com/user-attachments/files/22890634/Recording.13.10.2025.at.20_58_05.js)

**Comment by ollm** [comment]
It seems that the problem is related to `sharp`, https://github.com/lovell/sharp/issues/4348#issuecomment-3395738731. The best thing you can do for now is to use the Flathub version, which is not affected by this issue at the moment.

#### Install OpenComic from flathub

```
sudo pacman -S flatpak
flatpak install flathub app.opencomic.OpenComic
```

I'll keep an eye on https://github.com/lovell/sharp/issues/4348#issuecomment-3399560351 to see if it can be resolved.

**Comment by Envy91122** [comment]
Thanks! Version `1.6.3` from flatpak is working without problems!
